spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.211/sell?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.211
    port: 6379
server:
  servlet:
    context-path: /sell
wechat:
  openAppId: wx2f59f217c429cbda
  openAppSecret: 9d5c1ef2f46c8f017102a63ecc735041
  mpAppId: wx2f59f217c429cbda
  mpAppSecret: 9d5c1ef2f46c8f017102a63ecc735041
